name: comic_reader
description: A Flutter package for reading and parsing comic book archives (CBZ, CBT, etc.).
version: 0.3.0
homepage: https://github.com/lkrjangid1/comic_reader

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.0
  path: ^1.8.0
  path_provider: ^2.0.10
  photo_view: ^0.14.0
  file_picker: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # No assets included in the package

screenshots:
  - description: 'Ui of the comic reader'
    path: example/screenshots/exe.png